# One ephemeral environment per dev/* branch.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-dev
resources:
- ../base/ephemeral
labels:
- pairs:
    environment: dev
  includeSelectors: false
patches:
- target:
    kind: ResourceSetInputProvider
    name: workload-branches
  patch: |
    - op: replace
      path: /spec/filter/includeBranch
      value: "^dev/.+"
    - op: replace
      path: /spec/defaultValues/env
      value: dev
    - op: replace
      path: /spec/defaultValues/replicas
      value: 1
